#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmachine vscode monitor stop"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local service_name="vscode_protect"

  zdaemon stop $service_name
}

run() {
  core $@
}

run $@
