#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmachine frp <args...>"
  echo ""
}

check_dependencies() {
  which zvscode >> /dev/null 2>&1
  if [ "$?" != "0" ]; then
    zmicro install frp
  fi
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  check_dependencies

  zmicro frp $@
}

run() {
  core $@
}

run $@
