#!/bin/bash

# os::memory_usage() {
#   local TOTAL=$(free -m | grep Mem | awk '{print $2}')
#   local AVAILABLE=$(free -m | grep Mem | awk '{print $7}')
#   local USED=$((TOTAL - AVAILABLE))

#   local usage=$(($USED * 100 / $TOTAL))

#   echo -e "${usage}"
# }

# os::cpu_usage() {
#   local usage=`top -bn 1 -i -c | grep Cpu | awk '{print $2}'`

#   echo -e "${usage}"
# }


# export -f os::memory_usage
# export -f os::cpu_usage
