#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmachine frp client <args...>"
  echo ""
}

dependencies_check() {
  which frpc >>/dev/null 2>&1
  if [ "$?" = "0" ]; then
    return
  fi

  zmicro package install frp
}

core() {
  dependencies_check

  frpc $@
}

run() {
  core $@
}

run $@
